version: '2'
services:
  database:
    container_name: portable-oracle12c
    image: oracle/database:12.2.0.1-ee
    environment:
      - "ORACLE_SID=ORCLCDB"
      - "ORACLE_PDB=ORCL"
      - "ORACLE_PWD=123456"
      - "ORACLE_MEM=4000"
    volumes:
      - ./oradata:/opt/oracle/oradata # persistent oracle database data.
    ports:
      - 1521:1521
      - 8080:8080
      - 5500:5500
